config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "urls#new"

  resources :urls, only: [:index, :new, :create] do
    member do
      get :details
    end
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :urls, only: [:index, :create, :show, :destroy]
    end
  end

  match '/:key', to: 'urls#show', as: 'shortned', via: [:get, :post]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url.rb
class Url < ApplicationRecord

end

app/controllers/api/api_controller.rb
class Api::ApiController < ApplicationController
  skip_before_action :verify_authenticity_token

  rescue_from Exception, with: :internal_server_error
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  def record_not_found(exception)
    error = error_response(
      message: exception.to_s.split(' with').first,
      type: 'ResourceNotFound',
      data: { backtrace: exception.backtrace.unshift(exception.to_s) },
      code: 404
    )
    render json: error, status: 404
  end


  private

    def error_response(message:, type:, code: nil, trace_id: nil, status: 'failed', data: nil, errors: nil)
      {
        data: data,
        errors: errors,
        type: type, 
        code: code,
        message: message,
        status: status
      }
    end

    def success_response(data: nil, message: nil, status: 'success')
      { data: data, message: message, status: status }
    end

    def internal_server_error(exception)
      response = error_response(
        message: 'Something Went Wrong!',
        type: 'InternalServerError',
        data: { backtrace: exception.backtrace.unshift(exception.to_s) },
        code: 500
      )
      render json: response, status: 500
    end

end

app/controllers/api/v1/urls_controller.rb
class Api::V1::UrlsController < Api::V1::VersionController
  before_action :set_url, only: [:show, :destroy]

  def index
    @urls = Url.all
  end

  def show
  end

  def destroy
    @url.present? && @url.destroy
  end

  def create
    service = CreateShortUrlService.new(url: params[:url].to_s)

    if service.valid?
      service.call
      @url = service.url_object
      render status: :created
    else
      body = error_response(message: service.errors.full_messages.join,
        errors: service.error_body, type: 'ArgumentError', code: 1)
      render json: body, status: :unprocessable_entity
    end
  end

  private

    def set_url
      @url = Url.find(params[:id])
    end
end

app/controllers/api/v1/version_controller.rb
class Api::V1::VersionController < Api::ApiController

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :set_url, only: [:details]

  def index
    @urls = Url.all
  end

  def new
  end

  def create
    service = CreateShortUrlService.new(url: params[:url])

    if service.valid?
      service.call
      redirect_to details_url_path(service.url_object)
    else
      flash.now[:error] = service.errors.full_messages.join(', ')
      render :new
    end
  end

  def details
  end

  def show
    @url = Url.find_by(key: params[:key])
    redirect_to @url.url
  end

  private

    def set_url
      @url = Url.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortner</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all' %>


    <%= javascript_include_tag 'application' %>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">Url Shortner</a>
        </div>
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to "Home", new_url_path %></li>
          <li><%= link_to "Show Urls", urls_path %></li>
        </ul>
      </div>
    </nav>

    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/urls/details.html.erb
<div class="container-fluid">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-default">
      <table class="table">
        <tr>
          <th>Target Url</th>
          <td><%= link_to @url.url, @url.url %></td>
        </tr>
        <tr>
          <th>Shortened Url</th>
          <td><%= link_to shortned_url(key: @url.key), shortned_url(key: @url.key) %></td>
        </tr>
      </table>

      <div class="panel-footer">
        <%= link_to "Shorten Another Url", new_url_path, class: 'btn btn-primary pull-right' %>
        <%= link_to "Show All Urls", urls_path, class: 'btn btn-default pull-right mr-5' %>
        <div class="clearfix"></div>
      </div>
    </div>
  </div>
</div>

app/views/urls/index.html.erb
<div class="container">
  <div class="col-md-12">
    <div class="panel panel-default">
      <table class="table">
        <tr>
          <th>Target Url</th>
          <th>Shortened Url</th>
        </tr>

        <% @urls.each do |url| %>
          <tr>
            <td><%= link_to url.url, url.url %></td>
            <td><%= link_to shortned_url(key: url.key), shortned_url(key: url.key) %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/urls/new.html.erb
<div class="container-fluid">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <h3>Shorten your links</h3>
        <%= form_tag urls_path do %>
          <div class="form-group form-group-md">
            <%= label_tag "url", nil, class: "sr-only" %>
            <%= text_field_tag :url, params[:url], class: 'form-control', placeholder: 'Your original URL here', autocomplete: 'off' %>

            <% if flash[:error].present? %>
              <div class="error-text">
                <%= flash[:error] %>
              </div>
            <% end %>
          </div>
          <%= submit_tag 'SHORTEN URL', class: 'btn-primary btn' %>
        <% end %>
      </div>
    </div>
  </div>
</div>